name: Generate TikTok Video

on:
  workflow_dispatch:
    inputs:
      story_text:
        description: "Inserisci qui la tua storia"
        required: true
        default: "Era una notte buia e tempestosa..."

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script
      env:
        PEXELS_API_KEY: ${{ secrets.PEXELS_API_KEY }}
        STORY_TEXT: ${{ github.event.inputs.story_text }}
      run: python main.py

    - name: Upload video artifact
      uses: actions/upload-artifact@v3
      with:
        name: output-video
        path: output_tiktok.mp4
